# Generated by Django 2.2.1 on 2020-01-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
